### ISSUE TITLE
How do I do a partial match with the full-text search?

### ISSUE THREAD

**Issue by hsb-tonmoy** [testdrivenio/django-postgres-elasticsearch#2]
Hi! I have implemented a full-text search on my project following your guide. I have done everything till the Highlighting section. The only problem is that the search is only returning exact matches. 

For example, let's say a record has the text `Hello, my name is George.` inside its body. If I search using the following queries, it will bring up that record:

```
hello my name is George
hello George is my name
HELLO IS NAME MY GEORGE
```

But, it won't work if I use the following:

```
hello my name is Geo
George is my name hello Michael
```

Dumb examples but hopefully I was able to explain what I'm trying to say. Basically, I want the search to return partial matches as well as exact matches but rank the exact ones higher, of course.

This is how my model looks: [https://gist.github.com/hsb-tonmoy/0d489f20cdc7b9a94812f140ba15749f](https://gist.github.com/hsb-tonmoy/0d489f20cdc7b9a94812f140ba15749f)

This is how I'm filtering: [https://gist.github.com/hsb-tonmoy/cf79e9ba5d4f9fd4527fc79149627fa2](https://gist.github.com/hsb-tonmoy/cf79e9ba5d4f9fd4527fc79149627fa2)

**Comment by ParentJA** [comment]
Hi Tonmoy,

Thanks for reaching out. Can you possibly upload your entire project to
GitHub and send me the link? Also, is it possible to dump your DB and
include that too? You can use the Django management command for that part.
My first thought is that the database is only indexing on English roots, so
proper names like “George” won’t be included in that. There are ways you
can handle that though, and I’d be happy to help guide you in the right
direction!

Jason

**Comment by ParentJA** [comment]
Just looked at the links you posted. The filter fields and the filter class
might be competing with each other. If you send me the project and dataset
then I can debug, thanks!

**Comment by hsb-tonmoy** [comment]
Yes, of course. 

Github https://github.com/hsb-tonmoy/engmedapp-django
DB: https://raw.githubusercontent.com/hsb-tonmoy/files/master/db.sql

Thank you for your help.

**Comment by ParentJA** [comment]
Thanks, I’ll take a look after work and should get back to you in a day.

**Comment by ParentJA** [comment]
You can't use both filterset_fields and filterset_class in the same API.
(See
https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html#using-the-filterset-fields-shortcut.)
The filterset you sent in the Gist is different than the one you sent in
the repo, so it looks like you may have already fixed it? I built your
project and the full-text search is working. For example I searched the
word "collapse" (http://localhost:8000/questions/list/?query=collapsed) and
it returned record with ID=70d48cf9-c2bb-4c22-9723-436c8ea2288a, which
matched on the word "collapsing". "Collapsed" and "collapsing" have the
same root, so the full-text search was successful.

Hope that helps!

**Comment by hsb-tonmoy** [comment]
Thank you very much again. You're right, I removed filterset_fields because it was redundant (I already have filterset_class). 
Full-text search also works fine but I was actually hoping to achieve multi-worded search instead of just one-word query. I don't know if you're familiar with Chegg, I was actually trying to do something like Chegg's search.

For example, if I search for `If I hammered and flattened a penny`, I'll get a result:

![image](https://user-images.githubusercontent.com/35843150/145337970-37b76dff-a5f9-406d-84f1-1681746b9732.png)

but if I search for `If I hammered and flattened a coin`, I won't get anything back:

![image](https://user-images.githubusercontent.com/35843150/145338015-29d8e8e3-a826-45a4-ab37-2ee8821bf4c4.png)

I was just wondering if you could kindly assist me in making sure that my API returns results even if all the words aren't exact matches. (Partial-match basically.)

Thanks again. I appreciate your efforts.

**Comment by ParentJA** [comment]
Ah I see. Let me take a look this weekend. Maybe this will inspire a blog
post or a course update from me too. Have you done any research into multi
word search yet? It might have something to do with AND-ing the search
terms together vs. OR-ing them. Have you looked into Elasticsearch yet or
are you set on using Postgres?

**Comment by hsb-tonmoy** [comment]
I think at this point in my project, Elasticsearch is bit of an overkill. I'll stick to Postgres for now. I'll try and solve this on my own, I'll share the solution if I can come up with one. Although, searching isn't my forte at all haha.

Thanks for your help, again.
